<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <SupportedOSPlatformVersion>10.0.19041.0</SupportedOSPlatformVersion>
    <UseWindowsForms>true</UseWindowsForms>
    <UseWinRT>true</UseWinRT>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <AssemblyName>FellrnrHeatMonitor</AssemblyName>
    <RootNamespace>FellrnrHeatMonitor</RootNamespace>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <ApplicationIcon>FellrnrHeatMonitor.ico</ApplicationIcon>
  </PropertyGroup>
  <ItemGroup>
    <Content Include="FellrnrHeatMonitor.ico" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="System.IO.Ports" Version="8.0.0" />
  </ItemGroup>
</Project>
